### ISSUE TITLE
build error : linking with `cc` failed

### ISSUE THREAD

**Issue by muralikodali** [user827/xaskpass#1]
build error occurred.

[log file](https://github.com/user827/xaskpass/files/5648422/xaskpass_builderror.txt) attached

**Comment by user827** [comment]
@muralikodali It says it cannot find xcb-errors. Do you have xcb-util-errors installed? Which disto are you using? I appreciate the report.

**Comment by muralikodali** [comment]
Thanks for pointing the error. After installing xcb-util-errors, build process went on smoothly without error.

My distro is Arch linux.
