### ISSUE TITLE
[BUG] xaskpass crashes Xorg server

### ISSUE THREAD

**Issue by prephyte** [user827/xaskpass#2]
After updating my xorg-server to 21.1.2-2, starting xaskpass crashes my server. Here is what xaskpass prints to console before crashing the server.

```
WARN - event cycle took 14762μs
ERROR - X11 connection: Unknown connection error (IoError(Custom { kind: Other, error: UnknownError }))
```
idk what to add here, if you need additional info, just tell me about it

**Comment by user827** [comment]
Can you start it as `xaskpass -vvd 2> xasklog.txt` and then attach the generated log file?

I think the problem is most likely in the server rather than in xaskpass because it seems weird that a client could crash the server.  I also updated my xorg-server in arch linux to 21.1.2-2 but cannot reproduce this.

**Comment by prephyte** [comment]
[xasklog.txt](https://github.com/user827/xaskpass/files/7774581/xasklog.txt)
Here is my log file. Also I just remembered that I updated nvidia driver, so possibly that is the cause of this? nvidia, fk u....

**Comment by user827** [comment]
It could be a driver issue. One thing you could try is to set `depth = 24` in the settings.

**Comment by prephyte** [comment]
`depth = 24` doesn't seem to help :( do you have any other ideas, or should we just close this and curse at nvidia once more?

**Comment by user827** [comment]
It can be open if there is an issue. If the problem is with the proprietary drivers I can try to reproduce the issue with such setup later.

**Comment by user827** [comment]
Can you tell what window manager were you using? Also can you get any error message out of X for example in journalctl or by starting the server while appending `&> xorglog.txt` at the end of its starting command e.g `startx &> xorglog.txt`?

**Comment by prephyte** [comment]
hey, sorry for making you wait 4 days, I use i3-gaps, here is my xorg.log
[xorg.log](https://github.com/user827/xaskpass/files/7786750/xorg.log)

**Comment by user827** [comment]
Thanks! I think it's this issue: https://bugs.archlinux.org/task/73031 and we'll just have to wait for nvidia to release an update or maybe it's best to downgrade the driver.

**Comment by prephyte** [comment]
well, thanks) guess my only option is just waiting, cuz previous nvidia driver had some opengl rendering issues, that are fixed here. thanks for putting your time into this :) gl
